from pydantic import BaseModel, Field


class RuleCitation(BaseModel):
    """A citation to a specific Living Rules Reference rule.

    Only ``rule_id`` (e.g. ``"58.4"``) and the model's short ``relevance`` note
    are stored here — the *quoted text* is looked up from the retrieved passages
    in the job payload, never generated by the model. That, plus post-hoc
    validation that every cited ``rule_id`` was actually retrieved, makes
    fabricated quotes impossible by construction.
    """

    rule_id: str = Field(description="LRR rule number this answer relies on, e.g. '58.4'.")
    relevance: str = Field(
        default="",
        description="One short phrase on why this rule is relevant to the answer.",
    )


class RulesAnswer(BaseModel):
    """Validated structure for a Rules Q&A response."""

    answer: str = Field(description="Direct answer to the rules question.")
    assumptions: list[str] = Field(
        default_factory=list,
        description="Assumptions made when interpreting the question.",
    )
    rule_basis: list[str] = Field(
        default_factory=list,
        description="Rules, sections, or concepts the answer is based on.",
    )
    caveats: list[str] = Field(
        default_factory=list,
        description="Edge cases or caveats the player should be aware of.",
    )
    # --- Grounding (RAG, additive & backward compatible) --------------------
    citations: list[RuleCitation] = Field(
        default_factory=list,
        description="LRR rules actually used, cited by rule number. Post-validated "
        "against the retrieved passages; any invented rule_id is dropped.",
    )
    grounded: bool = Field(
        default=False,
        description="True when the answer is backed by cited rules-reference "
        "passages; False when answered from general knowledge (e.g. out-of-corpus "
        "Discordant Stars content).",
    )
    needs_exact_text: bool = Field(
        default=False,
        description="True if answering confidently would require the exact card/rule text.",
    )

    @classmethod
    def fallback_from_text(cls, text: str) -> "RulesAnswer":
        """Wrap a plain-text model reply when structured output is unavailable.

        A fallback answer is never grounded — it came straight from the model
        without validated citations.
        """
        return cls(answer=text.strip(), grounded=False)

    def to_display_text(self) -> str:
        """Render a readable, plain-text version for the current frontend."""
        parts = [self.answer.strip()]
        if self.citations:
            parts.append("Cited rules:\n" + _bullets(
                f"LRR {c.rule_id}" + (f" · {c.relevance}" if c.relevance else "")
                for c in self.citations
            ))
        if self.rule_basis:
            parts.append("Rule basis:\n" + _bullets(self.rule_basis))
        if self.assumptions:
            parts.append("Assumptions:\n" + _bullets(self.assumptions))
        if self.caveats:
            parts.append("Caveats:\n" + _bullets(self.caveats))
        if self.needs_exact_text:
            parts.append(
                "Note: a fully confident answer would require the exact "
                "card/rule text."
            )
        return "\n\n".join(p for p in parts if p)


def _bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items if str(item).strip())
